### ISSUE TITLE
Palm tree leaf decay

### ISSUE THREAD

**Issue by jhcole** [FozLand/moretrees#1]
The leaf decay radius for palm trees seem to be too big.

They also don't seem to care what type of trunk is near by, but fixing that part would be an enhancement.

**Comment by mootpoint** [comment]
radius looks like it was already changed in fozland branch, a radius of 12 fits the entire palm tree and removes about 6 nodes from diameter that were unneeded. Fozland branch is set to 10 radius. that should have fixed the problem

**Comment by fozolo** [comment]
This is fixed.  Upstream changed leaf decay to use the API that MTG now provides.  This means palm leaves will look for only the correct trunk type.  However, the default radius of 10 was found to be too small some of the time.  Increasing `moretrees.palm_leafdecay_radius` to 12 in the `moretrees_settings.txt` file seems to be sufficient.
